# Generated by Django 5.1.3 on 2024-11-18 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usermodel_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='role',
        ),
    ]
