# Generated by Django 5.1.3 on 2024-11-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(db_index=True, default='', max_length=255)),
                ('last_name', models.CharField(db_index=True, default='', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['first_name', 'last_name'], name='employees_e_first_n_66982f_idx')],
            },
        ),
    ]
