# Generated by Django 5.1.3 on 2024-11-18 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.IntegerField(db_index=True)),
                ('image', models.ImageField(upload_to='employees/attendances/')),
                ('datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('score', models.FloatField(db_index=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employeemodel')),
            ],
            options={
                'indexes': [models.Index(fields=['datetime', 'employee'], name='employees_e_datetim_859e7f_idx')],
            },
        ),
    ]
