# Generated by Django 5.1.3 on 2024-11-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeeattendancemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='employees/'),
        ),
    ]
