# Generated by Django 5.1.3 on 2024-11-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen', models.DateTimeField(auto_now=True, db_index=True)),
                ('visit_count', models.IntegerField(db_index=True, default=1)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], max_length=10)),
                ('age', models.IntegerField()),
                ('image', models.ImageField(upload_to='clients/')),
            ],
            options={
                'indexes': [models.Index(fields=['first_seen', 'last_seen', 'visit_count'], name='clients_cli_first_s_fd4a47_idx')],
            },
        ),
    ]
